### ISSUE TITLE
Add Support for HS220 Dimmer

### ISSUE THREAD

**Issue by rwmccoy** [GadgetReactor/pyHS100#114]
I have the new HS220 dimmer. I can use it as a switch, but dimming functionality is not supported.

The devices seem to be in short supply but I will be glad to do any testing on mine. If information is needed on how the dimming commands are implemented, I will try to help with that as well.

**Comment by rytilahti** [comment]
It could be that these use the same protocol as the bulbs, so could you please try `pyhs100 --ip <your device ip> --debug --bulb brightness` and then the same but adding like `50` at the end to see if it changes the brightness?

**Comment by rwmccoy** [comment]
I'm using Home Assistant to control this switch. I changed the YAML file to point to the switch as a HS100 and got this error message:
Could not read state for TP-Link Light: Error on smartlife.iot.smartbulb.lightingservice.get_light_state: {'err_code': -1, 'err_msg': 'module not support'} 

If I need to use pyhs100 to provide the information you need, let me know and I'll figure out how to compile and execute your requested command.

**Comment by JsChiSurf** [comment]
FYI, I just installed an HS220 today, so figured I see what 'pyhs100' returns, this is what I receive when running the 'debug' test:

pyhs100 --ip 192.168.1.116 --debug --bulb brightness
Error: no such option: --bulb

However, if I run --debug with no argument, I can see the following JSON data ouput with references to "brightness" values:

DEBUG:pyHS100.protocol:> (31) {"system": {"get_sysinfo": {}}}
DEBUG:pyHS100.protocol:< (743) {"system":{"get_sysinfo":{"sw_ver":"1.4.8 Build 180109 Rel.171240","hw_ver":"1.0","mic_type":"IOT.SMARTPLUGSWITCH","model":"HS220(US)","mac":"B0:4E:26:A9:20:DF","dev_name":"Smart Wi-Fi Dimmer","alias":"Chandelier","relay_state":0,"brightness":25,"on_time":0,"active_mode":"none","feature":"TIM","updating":0,"icon_hash":"","rssi":-53,"led_off":0,"longitude_i":-876739,"latitude_i":419352,"hwId":"84DCCF37225C9E55319617F7D5C095BD","fwId":"00000000000000000000000000000000","deviceId":"800695154E6B882428E30F850473F34019A9E999","oemId":"3B13224B2807E0D48A9DD06EBD344CD6","preferred_state":[{"index":0,"brightness":100},{"index":1,"brightness":75},{"index":2,"brightness":50},{"index":3,"brightness":25}],"next_action":{"type":-1},"err_code":0}}}

**Comment by JsChiSurf** [comment]
So, as I follow up, I realized since I didn't have an explicit "bulb" option, that I was not running the latest version (0.3.0), so I upgraded and re-ran.

Using:

 pyhs100 --ip 192.168.1.116 --debug --bulb brightness

I get a bunch of data back:

{"system":{"get_sysinfo":{"sw_ver":"1.4.8 Build 180109 Rel.171240","hw_ver":"1.0","mic_type":"IOT.SMARTPLUGSWITCH","model":"HS220(US)","mac":"B0:4E:26:A9:20:DF","dev_name":"Smart Wi-Fi Dimmer","alias":"Chandelier","relay_state":0,"brightness":34,"on_time":0,"active_mode":"none","feature":"TIM","updating":0,"icon_hash":"","rssi":-58,"led_off":0,"longitude_i":-876739,"latitude_i":419352,"hwId":"84DCCF37225C9E55319617F7D5C095BD","fwId":"00000000000000000000000000000000","deviceId":"800695154E6B882428E30F850473F34019A9E999","oemId":"3B13224B2807E0D48A9DD06EBD344CD6","preferred_state":[{"index":0,"brightness":100},{"index":1,"brightness":75},{"index":2,"brightness":50},{"index":3,"brightness":25}],"next_action":{"type":-1},"err_code":0}}}
Brightness: None

Which is probably not what is expected.  Still, trying to set a value using the brightness option by calling the "plug" (dimmer switch) as if it were a "bulb":

pyhs100 --ip 192.168.1.116 --debug --bulb brightness 50 

I actually receive a response of:

Setting brightness to 50

Followed immediately by the same data dump above, but this command has no actual impact on the switch / attached light, and re-querying for the data shows the original brightness level unchanged.

I can, however, actually run without an error returned at all, the command:

pyhs100 --ip 192.168.1.116 --debug --plug brightness 50

With a message returned of:

Setting brightness to 50

But again, no impact on the actual state.

**Comment by rytilahti** [comment]
Interesting, compared to the bulbs it has the brightness (although also `preferred_state`s as the bulbs, I assume) on the `system` level. You could try if something like following works, assuming their API is consistent:
```
from pyHS100 import SmartPlug

dev = SmartPlug("192.168.1.116")
print("device: %s" % dev)
dev._query_helper("system", "set_brightness", {"brightness": 100})
```

edit: it looks like there should also be a check that brightness is not allowed when using `--plug`. I'm unsure if this should be part of the bulb or the plug, but I suppose bulb would be the proper place to control these devices.

**Comment by JsChiSurf** [comment]
Yes, I thought it was strange that --plug didn't bark at me when I sent a brightness value in.

I ran the python script above with output from the print statement:

device: <SmartPlug at 192.168.1.116 (Chandelier), is_on: True - dev specific: {'LED state': True, 'On since': datetime.datetime(2018, 4, 3, 21, 6, 35, 231339)}>

But no impact on actually setting a value for brightness.

**Comment by JsChiSurf** [comment]
So, in digging in on this a little more, and looking through the Android app I decompiled, it would appear to me, on the surface, that there may need to be a 3rd type, in addition to SmartPlug and SmartBulb (SmartDimmer ?).

I see the following command for setting brightness:

dimmerCommand.dimmer.set_brightness

Note, this is only for dimming / brightness.  All other commands for the 'switch' use 'SmartPlug'.

When I compare this to a similar command for setting relay status for a plug I see:

smartPlugCommand.system.set_relay_state

On a whim I wanted to see what happened issuing the following:

dev._query_helper("dimmer", "set_brightness", {"brightness":100})

Which returns the error:

pyHS100.smartdevice.SmartDeviceException: Error on dimmer.set_brightness: {'err_msg': 'module not support', 'err_code': -1}

**Comment by rytilahti** [comment]
The dimmer there is just a name of the variable, the name of the 'module' (such as 'system' for general, and 'smartlife.iot.smartbulb.lightingservice' for lights) is required. The easiest way to find it out is likely simply doing a packet capture and using the wireshark dissector which can be found here: https://github.com/softScheck/tplink-smartplug#wireshark-dissector .

I'm a bit hesitant to add a new class without having a more complete view on how the device works (and how much it shares with bulb and plug), but that's not completely out of question.

**Comment by JsChiSurf** [comment]
Yeah, I played with the dissector, and got no where, realizing (and please correct me if I am wrong), that the only direct communication I have is between the dimmer switch and my phone, so using my laptop to "listen in" via wireshark showed none of the traffic I was hoping to see, especially the custom fields as defined by the dissector.

However, after your reference to looking for the "module" name, it became relatively trivial to parse through the decompiled Android code for the existing 'smartlife.iot.smartbulb.lightingservice' module for bulbs and 'system' for general, to find the correct module for Dimmer, which is 'smartlife.iot.dimmer'.

So, after seeing this I tried to run the following:

dev._query_helper("smartlife.iot.dimmer", "set_brightness", {"brightness":20})
dev._query_helper("smartlife.iot.dimmer", "set_brightness", {"brightness":100})

And they work PERFECTLY!

*Note, while it may seem obvious, the switch must first be on in order to then set brightness.

**Comment by rytilahti** [comment]
Glad to hear you got it working :-) As you can see in the smartbulb implementation, there is a separate implementation for changing light brightness when the light is off, that's most likely the case in the dimmer too.

Regarding to the packet captures, you indeed need to do the capture between your mobile and the device, e.g. on your router.

**Comment by JsChiSurf** [comment]
Thanks for confirming regarding wireshark.  I wasted a lot of time on that one :-)

Regarding the smart bulb, I see when querying for bulb brightness a difference in syntax when the bulb is on or off (it appears), but not for when setting brightness it seems.

For my own personal use, I'm just going to send an 'on' command first, before trying to set any brightness levels.

As expected, I can query for "brightness" of the dimmer switch, regardless of on/off state by just dumping:  sys_info['brightness']
