### ISSUE TITLE
bulb hue is limited to 255 instead of 360

### ISSUE THREAD

**Issue by nkonopinski** [GadgetReactor/pyHS100#130]
Unless this was intentional because you don't want people having pink lights ¯\_(ツ)_/¯
I tried to make a pr but I don't have access. Here's a diff for the fix
```
diff --git a/pyHS100/smartbulb.py b/pyHS100/smartbulb.py
index 8f0bce6..5591974 100644
--- a/pyHS100/smartbulb.py
+++ b/pyHS100/smartbulb.py
@@ -142,10 +142,10 @@ class SmartBulb(SmartDevice):
         if not self.is_color:
             return None
 
-        if not isinstance(state[0], int) or not (0 <= state[0] <= 255):
+        if not isinstance(state[0], int) or not (0 <= state[0] <= 360):
             raise SmartDeviceException(
                     'Invalid hue value: {} '
-                    '(valid range: 0-255)'.format(state[0]))
+                    '(valid range: 0-360)'.format(state[0]))
 
         if not isinstance(state[1], int) or not (0 <= state[1] <= 100):
             raise SmartDeviceException(
```

**Comment by kirichkov** [comment]
I tried to make a pr but I don't have access. Here's a diff for the fix

Probably you tried to push directly to this repository. Instead do the following:
1. fork this repository to your own github account
2. create a new branch on the forked repository
3. Push your changes to the forked repository's new branch
4. Create the pull request from your forked repo, to this repo.

We'll discuss the change there. Please also post the device model and firmware number you used for testing, because this might be due to firmware version differences and not an oversight. I can assure we don't mind people setting their bulbs to pink, or any other color 😄

**Comment by CBR-Greg** [comment]
I am having the same issue this a TP- link LB130 bulb with firmware 1.8.
Here is the error in my log if i try to select a red or pink from home assistant. 
![image](https://user-images.githubusercontent.com/44884293/48310511-07773080-e556-11e8-8bc3-fae99c41cc7b.png)

**Comment by annikajayuk** [comment]
I've created pull request #140; hopefully this is ok (thanks for the instructions).

**Comment by zackoch** [comment]
@annikajayuk @rytilahti - setting it to 359 makes it  so you can't use the color red(pink works though). Please see pr #141

**Comment by annikajayuk** [comment]
Ah, ok. I'd been using RGB 255, 0, 0 in Home Assistant scripts to get red, which worked for me anyway (I assume this gets converted to a hue of 0 degrees rather than 360), but I can see that the colour wheel in HA's UI uses 360.
