### ISSUE TITLE
Update README and prepare 0.3 release

### ISSUE THREAD

**Issue by rytilahti** [GadgetReactor/pyHS100#80]
This task is a proposal to start working towards a new release. I would propose we will make it 0.3 considering that this breaks the API and is the first release to drop python2 support from the code-base. A preliminary list of changes follows.

---

API break:
* Python2 support has been dropped.
* pyHS100/pyHS100.py has been splitted to smartdevice.py, smartplug.py and smartbulb.py, no one should have ever accessed these directly though.
* SmartPlugException is no more, SmartDeviceException is used by both SmartPlug and SmartBulb
* Discovery has been moved from TPLinkSmartHomeProtocol into its own class for easier 3rd party use.

Other changes:
* CLI tool supports device discovery and is usable without specifying device type or IP for testing
* CLI tool supports changing bulb-specific settings
* Library support & unit tests are extended to cover more devices.
  * Supported plugs: HS100, HS105, HS110
  * Supported switches: HS200
  * Supported bulbs: LB100, LB110, LB120, LB130

**Comment by rytilahti** [comment]
Considering we are breaking the API with this release, I think we should discuss whether we could also clean-up other parts of the API too. For instance, `identify()` returning a tuple is not nice and can potentially lead to problems if the user of the library is not careful enough, see [the example](https://github.com/GadgetReactor/pyHS100#library-usage).

**Comment by rytilahti** [comment]
LB100 sysinfo can be found from https://github.com/GadgetReactor/pyHS100/pull/58#issuecomment-304158705 (thanks again @kdschlosser!)

**Comment by kdschlosser** [comment]
Sorry I have not been able to do much with this recently.

But what I do have for ya that will possibly help is attached
[tests.zip](https://github.com/GadgetReactor/pyHS100/files/1206440/tests.zip)

This is what I have compiled thus far. there could still be some variations I do not know about

**Comment by kirichkov** [comment]
I agree on breaking `identify()`. Splitting it into two members - `identify_model()` and `features()` seems like a good idea, where the first returns a string with the model and features returns an array of features. To the best of my knowledge currently there are two features - energy monitor and time.

**Comment by kdschlosser** [comment]
in all honesty identify() is really not needed.

the user has the ability to create the identify tuple return very simply. 

    identification = (
        device.alias,
        device.model,
        device.features
    )

one of the reasons why i don't feel it is a necessity. I could understand if it was some kind of a complex thing to get this information or it required a lot of code. but neither is the case. I know identify() has been apart of the API but if you are willing to break it. then I suggest to remove it completely and let the user pick the bits they want to know about. and breaking the API by removing it would require them to do a text replacement on their code. for the above example. if you split identify() up there is more complexity. 

I would only add a has_timer property for the TIM just like the has_emeter works.

if you added the has_timer property then you could even consider removing the features property as this would become obsolete as well. 
 
@kirichkov 
does the property device.model return the model already? and would identify_model() return something different?  If they are the same you could do this to give the user the best of both worlds. the user would get the callable "identify_model". or they could use the attribute "model" as well

    def  identify_model(self):
        """
        Get model of the device
        :return: device model
        :rtype: str
        :raises SmartDeviceException: on error
        """
        return self.sys_info['model']

    model = property(identify_model)

**Comment by rytilahti** [comment]
The features are not currently being reported for anything except the plugs, which explicitly report them through `feature` key. This is something we should probably do though based on other keys in sysinfo for other models.

Tbh I would actually prefer to have `features` reporting an IntFlag (or similar) instead of currently used strings. Besides timer and meter we could also expose is_dimmable, is_color and so on through that for 3rd party users.

@kdschlosser what kind of advantages exposing it as a callable would have instead of keeping them as properties?

**Comment by kdschlosser** [comment]
i don't think there is a benefit, it was simply that  @kirichkov specified the callable identify_model to obtain the model number. i was suggesting a solution is all. 

what i have setup is i created a base class for bulbs, plugs, switches. and these classes have no options for things like emeter or timer, or color. then i created classes with the proper methods/properties for say color, and emeter. and then i created a class for each of the models and then subclassed the base class and any "option" classes. so has_emeter would simply do return isinstance(self, EMETER) the has_emeter, is_dimmable, is_color are all properties in the respective base classes.

I have a list of what model has what features somewhere. The reason i did this was in the specific model class i would override things like the mac. and the type. or time if those are not available. or require different code.

**Comment by kirichkov** [comment]
@rytilahti Why FlagInts and not simple True/False?

**Comment by rytilahti** [comment]
@kirichkov I was thinking it'd be nice to have a way to add more features where needed. But I agree that basic functionality should probably be made available through `is_X` or `has_X` type of getters.

@kdschlosser that sounds quite complicated and non-pythonic tbh (multi inheritance is not very widely used normally). Anyway, I find think that the base class (e.g. SmartBulb) could be inherited with another class which implements one/some methods implemented by the base class differently. Do you think there are enough differences to make it worth not simply to have if-elses for those checks in SmartBulb?

**Comment by kdschlosser** [comment]
i do not know i have happened across quite a few. and all of them appear to be in the newer devices. But the real question is are the changes device specific or firmware specific. that I do not have an answer for. But if the structure is right and they continue to change things up and remove features on any new devices it is far easier to follow then having to do a query of the device to obtain the model number in order to check and make sure of how it is supposed to handle the request. if there is an individual class for each model right out of the gate then there is no need to query the device for it's model number. but also form a support standpoint if it is a specific model number that is causing an issue with a specific property/method it is far easier to find/fix and also not have to worry about any changes potentially breaking all devices instead of a single model number. Because the change would be model number specific so to speak then all devices would not have to be checked for functionality of a single change to a property. only the one model

and i can understand your standpoint on multiple inheritance. because more often then not it gets done wrong.

At the present state of the number of differences... Possibly not... but you have to look at the number of changes that have occurred recently.. and will that pattern continue.. IDK, but i am one to hope for the best but plan for the worst. It's a suggestion to keep in the back of your mind. even something you could start tinkering with to see if you can come up with a solution that would meet the requirements that you want. these types of things don't get done overnight and they require a lot of thought and planning. so what you start looking at now could possibly be ready for the next batch of changes that TP-Link makes. instead of having to add more if then else. now I know this is not a big thing but having the property/method handle the differences does impact performance. Taking a hit once at creation is far better then every time the question gets asked. As an example look at Microsoft Windows.. if it could be rewritten how large and how much faster do you think it would be??? I bet it would be 30% smaller and almost 2 times faster. Now I know this isn't anything like MS Windows. But when they had to fix something, instead of rewriting they did the if then else thing as well and now look at the mess.

Not saying my solution is the right one. or the best one. or that it should even be used. But you should think of a better way of handling these changes that make it easier for yourself and others to find/add/fix

**Comment by rytilahti** [comment]
I don't think there are going to be many changes to the firmwares for older hardware, so I don't think that's going to be an issue. But if that'd be the case, we can always fix it later on. Querying the device in order to gain knowledge of supported features is needed currently anyway for the device discovery, I think that could be extended easily to ask for those device specific "modules" and act accordingly. At least with "emeter" the device will inform with an error when the feature is not supported, maybe it's the same for other "modules" like `smartlife.iot.*`? Anyway, in my opinion we should not be checking against models & versions where possible, but try to query the devices for supported features and offer those.

My point is, at the moment I'm seeing those "modules" which differ between versions, and my hope is that the devices will respond to (discovery) queries accordingly indicating if the feature is supported or not. I'm not saying that it would help us to avoid hard-coding some parts of the code, but I think we should avoid having device-specific code where possible and try to use & provide common interfaces.. Looking from this standpoint it makes more sense not to try to go for device specific classes but to try to find a way to to query device's features and expose functionality based on that. I'm not sure if this is feasible, and not having any other devices than a HS110 makes it kind of hard to test, but I think the `discover` should be extended and tested out if the information is readily available.

That being said, I have not yet had a deeper look into the files you provided (those probably should be added to the tests where possible? Thanks for those!), but to me it looks like those devices may be responsive for a discovery packets containing `smartlife.iot.*` modules. Maybe output from those (if this speculation I'm doing is not baseless) could be used to assign supported features like mentioned before?

Anyway, what I really would like to see is to have a new release at some point :-)

**Comment by kdschlosser** [comment]
Oh I would get a release out with the current fixes/updates.

Those files are based off of information I have managed to get from a variety of places. That being said, I am not 100% sure on the accuracy. but it is a starting point. I have checked with TP-Link as far as the feature sets. and those are correct. I started to "normalize" the information contained within them but did not finish. as an example I was going to make all of the mac addresses the same. things like that.

**Comment by rytilahti** [comment]
#82 adds tests for LB100, thanks @kdschlosser!

**Comment by kdschlosser** [comment]
no worries m8

**Comment by rytilahti** [comment]
Created #88, please test and scrutinize if you can before it'll be tagged and released. :-)

**Comment by kirichkov** [comment]
What's the timeline for release? I can run some tests against the HS110 over the weekend but I don't want to hold off a release, given you've probably already tested it :-)

**Comment by rytilahti** [comment]
I don't think we are in a hurry regarding to a release, but I just wanted to start get the ball rolling (and responses from people with other devices) before going to publish a broken release :-) I think we can plan to push it out in the beginning of the next week.

**Comment by kirichkov** [comment]
Let's hope someone with a bulb and a switch can provide some real world feedback :-)

**Comment by rytilahti** [comment]
Release is now done so let's close this and hope we are not going to get flooded with issues ;-)
